pdsensorvis/pdserver/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.conf import settings
from django.conf.urls import url
from django.views.generic import RedirectView
from django.views.static import serve

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", RedirectView.as_view(url="/sensors/", permanent=False)),
    path("sensors/", include("sensors.urls")),
    url(r"^data/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT}),
    path("accounts/", include("django.contrib.auth.urls")),
]

pdsensorvis/sensors/urls.py
from django.urls import path, re_path
from django.conf import settings
from django.conf.urls import url
from django.views.static import serve
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("search/", views.search_results, name="search-results"),
    path("patientdata/", views.PatientDataListView.as_view(), name="patientdata"),
    re_path(
        r"^patientdata/(?P<pk>\d+)$",
        views.PatientDataDetailView.as_view(),
        name="patientdata-detail",
    ),
    re_path(
        r"^patientdata/create/$", views.create_patientdata, name="create-patientdata"
    ),
    re_path(
        r"^patientdata/(?P<pk>[\w-]+)/create/wearable/$",
        views.create_wearabledata,
        name="create-wearabledata",
    ),
    re_path(
        r"^patientdata/(?P<pk>[\w-]+)/create/camera/$",
        views.create_cameradata,
        name="create-cameradata",
    ),
    re_path(
        r"^patientdata/(?P<pk>[\w-]+)/edit/$",
        views.edit_patientdata,
        name="edit-patientdata",
    ),
    re_path(
        r"^patientdata/(?P<pk>[\w-]+)/delete/$",
        views.delete_patientdata,
        name="delete-patientdata",
    ),
    path("wearabledata/", views.WearableDataListView.as_view(), name="wearabledata"),
    re_path(
        r"^wearabledata/(?P<pk>[\w-]+)$",
        views.WearableDataDetailView.as_view(),
        name="wearabledata-detail",
    ),
    re_path(
        r"^wearabledata/(?P<uuid>[\w-]+)/(?P<pk>\d+)$",
        views.WearableAnnotationDetailView.as_view(),
        name="wearableannotation-detail",
    ),
    re_path(
        r"^wearabledata/(?P<uuid>[\w-]+)/edit/$",
        views.edit_wearabledata,
        name="edit-wearabledata",
    ),
    re_path(
        r"^wearabledata/(?P<uuid>[\w-]+)/delete/$",
        views.delete_wearabledata,
        name="delete-wearabledata",
    ),
    re_path(
        r"^wearabledata/(?P<uuid>[\w-]+)/import/annotation/$",
        views.upload_wearable_annotations,
        name="upload-wearable-annotations",
    ),
    re_path(
        r"^wearabledata/(?P<uuid>[\w-]+)/create/$",
        views.create_wearable_annotation,
        name="create-wearable-annotation",
    ),
    re_path(
        r"^wearabledata/(?P<uuid>[\w-]+)/(?P<pk>\d+)/edit/$",
        views.edit_wearable_annotation,
        name="edit-wearable-annotation",
    ),
    re_path(
        r"^wearabledata/(?P<uuid>[\w-]+)/(?P<pk>\d+)/delete/$",
        views.delete_wearable_annotation,
        name="delete-wearable-annotation",
    ),
    path("cameradata/", views.CameraDataListView.as_view(), name="cameradata"),
    re_path(
        r"^cameradata/(?P<pk>[\w-]+)$",
        views.CameraDataDetailView.as_view(),
        name="cameradata-detail",
    ),
    re_path(
        r"^cameradata/(?P<uuid>[\w-]+)/edit/$",
        views.edit_cameradata,
        name="edit-cameradata",
    ),
    re_path(
        r"^cameradata/(?P<uuid>[\w-]+)/delete/$",
        views.delete_cameradata,
        name="delete-cameradata",
    ),
    re_path(
        r"^cameradata/(?P<pk>[\w-]+)/export/csv/$",
        views.export_annotations_csv,
        name="export-annotations-csv",
    ),
    re_path(
        r"^cameradata/(?P<pk>[\w-]+)/export/xls/$",
        views.export_annotations_xls,
        name="export-annotations-xls",
    ),
    re_path(
        r"^cameradata/(?P<pk>[\w-]+)/export/srt/$",
        views.export_annotations_srt,
        name="export-annotations-srt",
    ),
    re_path(
        r"^cameradata/(?P<uuid>[\w-]+)/(?P<pk>\d+)$",
        views.CameraAnnotationDetailView.as_view(),
        name="cameraannotation-detail",
    ),
    re_path(
        r"^cameradata/(?P<uuid>[\w-]+)/(?P<pk>\d+)/edit/$",
        views.edit_camera_annotation,
        name="edit-camera-annotation",
    ),
    re_path(
        r"^cameradata/(?P<uuid>[\w-]+)/(?P<pk>\d+)/delete/$",
        views.delete_camera_annotation,
        name="delete-camera-annotation",
    ),
    re_path(
        r"^cameradata/(?P<uuid>[\w-]+)/(?P<pk>\d+)/(?P<cid>\d+)/edit/$",
        views.edit_cameraannotation_comment,
        name="edit-cameraannotation-comment",
    ),
    re_path(
        r"^cameradata/(?P<uuid>[\w-]+)/(?P<pk>\d+)/(?P<cid>\d+)/delete/$",
        views.delete_cameraannotation_comment,
        name="delete-cameraannotation-comment",
    ),
    url(r"^data/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_URL}),
    url(r"^static/(?P<path>.*)$", serve, {"document_root": settings.STATIC_URL}),
    path(
        "myannotations/",
        views.CameraAnnotationByUserListView.as_view(),
        name="my-annotations",
    ),
]

pdsensorvis/sensors/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.utils import timezone
import uuid

ANNOTATION = (
    ("asm", "Asymmetry"),
    ("dst", "Dystonia"),
    ("dsk", "Dyskensia"),
    ("ebt", "En Bloc Turning"),
    ("str", "Short Stride Length"),
    ("mov", "Slow/Hesitant Movement"),
    ("pos", "Stooped Posture"),
    ("trm", "Tremor"),
    ("oth", "Other/Activity"),
)

FRAME_RATES = (
    ("NTSC_Film", 23.98),
    ("Film", 24),
    ("PAL", 25),
    ("NTSC", 29.97),
    ("Web", 30),
    ("PAL_HD", 50),
    ("NTSC_HD", 59.94),
    ("High", 60),
)


class PatientData(models.Model):
    id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=50, help_text="Patient first name")
    last_name = models.CharField(max_length=50, help_text="Patient last name")
    date_of_birth = models.DateField(help_text="Patient date of birth")
    notes = models.CharField(max_length=500, help_text="Notes regarding patient")

    class Meta:
        ordering = ["last_name"]
        permissions = (
            ("can_alter_patientdata", "Can create or edit patient data entries."),
        )

    def get_absolute_url(self):
        return reverse("patientdata-detail", args=[str(self.id)])

    def __str__(self):
        return f"{self.last_name}, {self.first_name}"


class WearableData(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        help_text="Unique ID for this wearable data",
    )
    patient = models.ForeignKey(
        "PatientData", on_delete=models.CASCADE, null=True, related_name="wearables"
    )
    filename = models.FileField(upload_to="wearable/", help_text="Wearable data file")
    time = models.DateTimeField(help_text="Session date & time")
    note = models.CharField(max_length=500, help_text="Note regarding wearable data")

    class Meta:
        ordering = ["patient", "-time"]
        permissions = (
            ("can_alter_wearabledata", "Can create or edit wearable data entries."),
        )

    def get_absolute_url(self):
        return reverse("wearabledata-detail", args=[str(self.id)])

    def __str__(self):
        return f"{self.patient} ({self.time})"


class CameraData(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        help_text="Unique ID for this wearable data",
    )
    patient = models.ForeignKey(
        "PatientData", on_delete=models.CASCADE, null=True, related_name="cameras"
    )
    filename = models.FileField(upload_to="camera/", help_text="Camera video file")
    framerate = models.CharField(
        max_length=9,
        choices=FRAME_RATES,
        default="Film",
        help_text="Video framerate",
    )
    time = models.DateTimeField(help_text="Session date & time")
    note = models.CharField(max_length=500, help_text="Note regarding camera data")

    class Meta:
        ordering = ["patient", "-time"]
        permissions = (
            ("can_alter_cameradata", "Can create or edit camera data entries."),
        )

    def get_absolute_url(self):
        return reverse("cameradata-detail", args=[str(self.id)])

    def __str__(self):
        return f"{self.patient} ({self.time})"

    def get_user_annotations(self):
        return self.c_annotations.filter(annotator=User)


class WearableAnnotation(models.Model):
    id = models.AutoField(primary_key=True)
    wearable = models.ForeignKey(
        "WearableData",
        on_delete=models.CASCADE,
        null=True,
        related_name="w_annotations",
    )
    frame_begin = models.PositiveIntegerField()
    frame_end = models.PositiveIntegerField()
    annotator = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    annotation = models.CharField(
        max_length=3,
        choices=ANNOTATION,
        default="oth",
        help_text="PD Symptom",
    )
    note = models.CharField(
        max_length=500, help_text="Note regarding annotation", null=True, blank=True
    )

    class Meta:
        ordering = ["frame_begin"]
        permissions = (
            (
                "can_alter_wearableannotation",
                "Can create or edit wearable annotations.",
            ),
        )

    def get_absolute_url(self):
        return reverse(
            "wearableannotation-detail", args=[str(self.wearable.id), str(self.id)]
        )

    def __str__(self):
        return f"{self.wearable} - ({self.frame_begin}-{self.frame_end}) - {self.get_annotation_display()}"


class CameraAnnotation(models.Model):
    id = models.AutoField(primary_key=True)
    camera = models.ForeignKey(
        "CameraData", on_delete=models.CASCADE, null=True, related_name="c_annotations"
    )
    time_begin = models.CharField(max_length=11, help_text="hh:mm:ss:ff")
    time_end = models.CharField(max_length=11, help_text="hh:mm:ss:ff")
    annotator = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    annotation = models.CharField(
        max_length=3,
        choices=ANNOTATION,
        default="oth",
        help_text="PD Symptom",
    )
    note = models.CharField(
        max_length=500, help_text="Note regarding annotation", null=True, blank=True
    )

    class Meta:
        ordering = ["camera", "time_begin"]
        permissions = (
            ("can_alter_cameraannotation", "Can create or edit camera annotations."),
        )

    def get_absolute_url(self):
        return reverse(
            "cameraannotation-detail", args=[str(self.camera.id), str(self.id)]
        )

    def __str__(self):
        return f"{self.camera} - ({self.time_begin}-{self.time_end}) - {self.get_annotation_display()}"


class CameraAnnotationComment(models.Model):
    id = models.AutoField(primary_key=True)
    annotation = models.ForeignKey(
        "CameraAnnotation", on_delete=models.CASCADE, related_name="comments"
    )
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    timestamp = models.DateTimeField(default=timezone.now)
    text = models.TextField()

    class Meta:
        ordering = ["annotation", "timestamp"]
        permissions = (
            (
                "can_alter_cameraannotation_comment",
                "Can create or edit camera annotation comments.",
            ),
        )

    def __str__(self):
        return self.text


class WearableDataPoint(models.Model):
    id = models.AutoField(primary_key=True)
    wearable = models.ForeignKey(
        "WearableData", on_delete=models.CASCADE, null=True, related_name="data_point"
    )
    frame = models.PositiveIntegerField()
    magnitude = models.FloatField()

    class Meta:
        ordering = ["frame"]
        permissions = (
            ("can_alter_wearabledata_point", "Can create or edit wearable data point."),
        )

    def __str__(self):
        return f"{self.wearable.id} - ({self.frame}, {self.magnitude})"

pdsensorvis/sensors/templates/sensors/camera_upload.html
{% extends "base.html" %}

{% block head_add %}
  <!-- Font Awesome -->
  <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
        integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
        crossorigin="anonymous">
  <!-- Moment.js -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.23.0/moment.min.js"
          integrity="sha384-bunvTFmdcliXRaa0bTXLrjm90OPHwbRgMLqTq9px8MTIpcfU60gnln3k+XsjG1th"
          crossorigin="anonymous"></script>
  <!-- Tempus Dominus Bootstrap 4 -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/css/tempusdominus-bootstrap-4.min.css"
        integrity="sha256-XPTBwC3SBoWHSmKasAk01c08M6sIA5gF5+sRxqak2Qs="
        crossorigin="anonymous" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/js/tempusdominus-bootstrap-4.min.js"
          integrity="sha256-z0oKYg6xiLq3yJGsp/LsY9XykbweQlHl42jHv2XTBz4="
          crossorigin="anonymous"></script>
{% endblock %}

{% block content %}
  <h1>Create New Camera Data</h1>
  <hr>
  <form action="" method="post" class="form-group" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
      <p><strong>Patient:</strong> {{ patientdata }} ({{ patientdata.date_of_birth }})</p>
      <div style="margin-top: 15px;"><strong>{{ form.filename.help_text }}: </strong>
        <span class='text-muted'><em>(.mp4 files only)</em></span>
      </div>
      <div class="form-control" style="width: 100%; height: 43px;">{{ form.filename }}</div>
      {{ form.filename.errors }}
      <div style="margin-top: 15px;"><strong>{{ form.framerate.help_text}}:</strong> {{ form.framerate }}
        <span class='text-muted'><em> (Note: Silhouette data is 24 FPS; change this only if certain)</em></span></div>
      {{ form.framerate.errors }}
      <div style="margin-top: 15px;"><strong>{{ form.time.help_text }}:</strong></div>
      <div class="input-group date" id="datetimepicker1" data-target-input="nearest" style="margin-top: 10px">
        {{ form.time }}
        <div class="input-group-append" data-target="#datetimepicker1" data-toggle="datetimepicker">
          <div class="input-group-text"><i class="material-icons buttonIconS">event</i></div>
        </div>
      </div>
      {{ form.time.errors }}
      <div style="margin-top: 10px;">
        <strong>{{ form.note.help_text}}:</strong>
        {{ form.note }}
        {{ form.note.errors }}
      </div>
    </table>
    <div class="buttons" style="margin-top: 10px">
      <input type="submit" value="Create" class="saveButton" />
      <input type="button" value="Cancel" class="cancelButton" onclick="window.history.back()" />
    </div>
  </form>
{% endblock %}

{% block jquery %}
  $(function () {
      $("#datetimepicker1").datetimepicker({
          format: 'DD/MM/YYYY HH:mm',
      });
  });
{% endblock %}

pdsensorvis/sensors/templates/sensors/cameraannotation_detail.html
{% extends "base.html" %}

{% load static %}

{% block content %}
  <div class="titleText">
    <h1>Patient:
      <a href="{{ cameraannotation.camera.patient.get_absolute_url }}" data-toggle="tooltip" data-placement="bottom"
         data-trigger="hover" title="Link to patient data page">{{ cameraannotation.camera.patient }}</a>
    </h1>
    {% if perms.sensors.can_alter_cameradata %}
      <button id="edit" class="titleButton controlButtonXL editButton"
              onclick="window.location.href='{% url 'edit-camera-annotation' cameraannotation.camera.id cameraannotation.id|stringformat:'i' %}'"
              data-toggle="tooltip" data-placement="bottom" data-trigger="hover"
              title="Edit Camera Annotation">
        <i class="material-icons buttonIconS">create</i>
        <span class="buttonText">Annotation</span>
      </button>
    {% endif %}
  </div>
  <p><em>Session Time:</em>
    <a href="{{ cameraannotation.camera.get_absolute_url }}" data-toggle="tooltip" data-placement="bottom"
       data-trigger="hover" title="Link to wearable data page">{{ cameraannotation.camera.time }}</a>
    <span class="vert-divider">|</span> <em>Note:</em> {{ cameraannotation.camera.note }}
  </p>

  <hr>
  <p><strong>Annotator:</strong> {{ cameraannotation.annotator }}</p>
  <p><strong>Times (h:m:s:f):</strong> {{ cameraannotation.time_begin }} - {{ cameraannotation.time_end }}</p>
  <p><strong>Annotation:</strong> {{ cameraannotation.get_annotation_display }}
  </p>
  {% if cameraannotation.note %}
    <p><strong>Note:</strong> {{ cameraannotation.note }}</p>
  {% endif %}
  <hr>
  <h4>Comments</h4>
  {% for comment in cameraannotation.comments.all %}
    <div class="comment">
      <strong>{{ comment.author }}</strong> <em>(Posted on: {{ comment.timestamp }})</em>
      {% if user.is_authenticated %}
        {% if comment.author == user %}
          <button id="annotation_{{ cameraannotation.id }}_edit" class="controlButtonXS editButton"
                  onclick='window.location.href="{% url 'edit-cameraannotation-comment' cameraannotation.camera.id cameraannotation.id comment.id %}"'>
            <i class="material-icons buttonIcon" data-toggle="tooltip" data-placement="bottom" data-trigger="hover"
               title="Edit comment">edit</i>
          </button>
        {% endif %}
      {% endif %}
      <p>{{ comment.text|linebreaks }}</p>
    </div>
  {% empty %}
    <p>No comments.</p>
  {% endfor %}
  <hr>
  <form method="POST" class="post-form">
    {% csrf_token %}
    <h6>Post new comment:</h6>
    {{ form.text }}
    <div>
      <button type="submit" id="post" class="controlButtonL saveButton">Post</button>
      <input type="button" value="Back to Video" class="controlButtonXL cancelButton"
             onclick="window.location.href='{{ cameraannotation.camera.get_absolute_url }}'" />
    </div>
  </form>
{% endblock %}

pdsensorvis/sensors/templates/sensors/cameraannotation_list_annotated_user.html
{% extends "base.html" %}

{% block content %}
  <h1>My Camera Annotations</h1>
  <hr>
  <div class="annotation-objects">
    <ul id="annotation-objects-list">
      {% for annotation in cameraannotation_list %}
        <li>
          <a href="{{ annotation.camera.get_absolute_url }}">{{ annotation.camera.patient }} ({{ annotation.camera.time }})</a><br>
          - ({{ annotation.time_begin}} - {{ annotation.time_end}}) -
          {{annotation.get_annotation_display}}{% if annotation.get_annotation_display == 'Other' %}: {{annotation.note}}{% endif %}
          <button id="annotation_{{ annotation.id }}_edit" class="controlButtonXS editButton"
                  name="{% url 'edit-camera-annotation' annotation.camera.id annotation.id|stringformat:"i" %}">
            <i class="material-icons" data-toggle="tooltip" data-placement="bottom" data-trigger="hover" style="font-size: 22px"
               title="Edit annotation">edit</i>
          </button>
          <a href="{{ annotation.get_absolute_url }}"><em>({{ annotation.comments.count }}
            comment{% if annotation.comments.count != 1 %}s{% endif %})</em>
          </a>
        </li>
      {% empty %}
        <p>You have no annotations.</p>
      {% endfor %}
    </ul>
  </div>
{% endblock %}

{% block jquery %}
  $('button', $('#annotation-objects-list')).each(function () {
      $(this).click(function() {
          if ($(this).attr('id').indexOf('edit') > -1) {
              document.location.href = this.name;
          }
      })
  });
{% endblock %}

pdsensorvis/sensors/templates/sensors/create_wearable_annotation.html
{% extends "base.html" %}

{% block content %}
  <div class="titleText">
    <h1>Create Wearable Annotation</h1>
  </div>
  <div>
    <em>Patient: </em>
    <a href="{{ wearable.patient.get_absolute_url }}" data-toggle="tooltip" data-placement="bottom"
               data-trigger="hover" title="Link to patient data page">{{ wearable.patient }}</a>
    <span class="vert-divider">|</span>
    <em>Session Time: </em>
    <a href="{{ wearable.get_absolute_url }}" data-toggle="tooltip" data-placement="bottom"
       data-trigger="hover" title="Link to wearable data page">{{ wearable.time }}</a>
    <span class="vert-divider">|</span>
    <em>Note:</em> {{ wearable.note }}
  </div>

  <hr>

  <form action="" method="post" class="form-group">
    {% csrf_token %}
    <table>
      <p><strong>Annotator:</strong> {{ user.username }}</p>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Create" class="saveButton" />
    <input type="button" value="Cancel" class="cancelButton" onclick="window.history.back()" />
  </form>
{% endblock %}

pdsensorvis/sensors/templates/sensors/edit_camera_annotation.html
{% extends "base.html" %}

{% block content %}
  <div class="titleText">
    <h1>Patient:
      <a href="{{ cameraannotation.camera.patient.get_absolute_url }}" data-toggle="tooltip" data-placement="bottom"
         data-trigger="hover" title="Link to patient data page">{{ cameraannotation.camera.patient }}</a>
      (Annotation)
    </h1>
  </div>
  <p><em>Session Time:</em>
    <a href="{{ cameraannotation.camera.get_absolute_url }}" data-toggle="tooltip" data-placement="bottom"
       data-trigger="hover" title="Link to wearable data page">{{ cameraannotation.camera.time }}</a>
    <span class="vert-divider">|</span> <em>Note:</em> {{ cameraannotation.camera.note }}
  </p>
  <hr>

  <form action="" method="post" class="form-group">
    {% csrf_token %}
    <table>
      <p><strong>Annotator:</strong> {{ cameraannotation.annotator }}</p>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Save" class="saveButton" />
    <input type="button" value="Cancel" class="cancelButton" onclick="window.history.back()" />
  </form>
  <form action="{% url 'delete-camera-annotation' cameraannotation.camera.id cameraannotation.id %}" method="post" class="form-group">
    {% csrf_token %}
    <input type="submit" value="Delete" class="deleteButton" onclick="return confirm('Are you sure you want to delete this annotation?');" />
  </form>
{% endblock %}

pdsensorvis/sensors/templates/sensors/edit_cameraannotation_comment.html
{% extends "base.html" %}

{% block content %}
  <div class="titleText">
    <h1>Edit Comment</h1>
  </div>
  <p>
    <em>Annotation: </em>
    {{ annotation.get_annotation_display }}{% if annotation.get_annotation_display == 'Other' %}: {{annotation.note}}{% endif %}
  </p>
  <hr>

  <form action="" method="post" class="form-group">
    {% csrf_token %}
    <table>
      <p><strong>Author:</strong> {{ annotation.annotator }} <em>({{ comment.timestamp }})</em></p>
      <p>{{ form.text }}</p>
    </table>
    <input type="submit" value="Save" class="saveButton" />
    <input type="button" value="Cancel" class="cancelButton" onclick="window.history.back()" />
  </form>
  <form action="{% url 'delete-cameraannotation-comment' camera.id annotation.id comment.id %}" method="post" class="form-group">
    {% csrf_token %}
    <input type="submit" value="Delete" class="deleteButton" onclick="return confirm('Are you sure you want to delete this comment?');" />
  </form>
{% endblock %}

pdsensorvis/sensors/templates/sensors/edit_patientdata.html
{% extends "base.html" %}


{% block content %}
  <h1>Edit Patient Data</h1>
  <hr>
  <form action="" method="post" class="form-group">
    {% csrf_token %}
    <table>
      <div><strong>{{ form.first_name.help_text }}:</strong><p>{{ form.first_name }}</p></div>
      <div><strong>{{ form.last_name.help_text }}:</strong><p>{{ form.last_name }}</p></div>
      <div><strong>{{ form.date_of_birth.help_text }}:</strong><p>{{ form.date_of_birth }}</p></div>
      <div style="margin-top: 10px;">
        <strong>{{ form.notes.help_text }}:</strong><p>{{ form.notes }}</p>
      </div>
    </table>
    <input type="submit" value="Save" class="saveButton" />
    <input type="button" value="Cancel" class="cancelButton" onclick="window.history.back()" />
  </form>
  <form action="{% url 'delete-patientdata' patientdata.id %}" method="post" class="form-group">
    {% csrf_token %}
    <input type="submit" value="Delete" class="deleteButton" onclick="return confirm('Are you sure you want to delete this patient data?');" />
  </form>
{% endblock %}

{% block jquery %}
  $(function () {
      $("#datetimepicker1").datetimepicker({
          format: 'DD/MM/YYYY',
      });
  });
{% endblock %}

pdsensorvis/sensors/templates/sensors/edit_wearabledata.html
{% extends "base.html" %}

{% block content %}
  <h1>Edit Wearable Data</h1>
  <hr>
  <form action="" method="post" class="form-group">
    {% csrf_token %}
    <table>
      <div><strong>Patient: </strong><a href="{% url 'patientdata-detail' wearabledata.patient.id %}">{{ wearabledata.patient }}</a></div>
      <div style="margin-top: 10px;"><strong>File: </strong>
        <a href="{{ media_url }}{{ wearabledata.filename }}">{{ wearabledata.filename }}</a>
      </div>
      <div style="margin-top: 10px;"><strong>{{ form.time.help_text }}:</strong><p>{{ form.time }}</p></div>
      <div style="margin-top: 10px;">
        <strong>{{ form.note.help_text }}:</strong><p>{{ form.note }}</p>
      </div>
    </table>
    <input type="submit" value="Save" class="saveButton" />
    <input type="button" value="Cancel" class="cancelButton" onclick="window.history.back()" />
  </form>
  <form action="{% url 'delete-wearabledata' wearabledata.id %}" method="post" class="form-group">
    {% csrf_token %}
    <input type="submit" value="Delete" class="deleteButton"
           onclick="return confirm('Are you sure you want to delete this patient data?');" />
  </form>
{% endblock %}

{% block jquery %}
  $(function () {
      $("#datetimepicker1").datetimepicker({
          format: 'DD/MM/YYYY',
      });
  });
{% endblock %}